### ISSUE TITLE
Testing Serial Port NPM Package

### ISSUE THREAD

**Issue by BalmaBrian** [LiquidPropulsionGroup/EngineWebServer#13]
Testing the serialport NPM package on the raspberry pi.

**Comment by BalmaBrian** [comment]
Server listening on: http://192.168.0.187:5000
message sent!
From Arduino: R

message sent!
From Arduino: R

```
(node:803) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/pi/EngineWebServer/node_modules/express/lib/response.js:771:10)
    at ServerResponse.json (/home/pi/EngineWebServer/node_modules/express/lib/response.js:264:10)
    at SerialPort.<anonymous> (/home/pi/EngineWebServer/src/routes/serial.ts:21:25)
    at SerialPort.emit (events.js:203:15)
    at SerialPort.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at SerialPort.Readable.push (_stream_readable.js:224:10)
    at binding.read.then (/home/pi/EngineWebServer/node_modules/@serialport/stream/lib/index.js:385:12)
(node:803) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:803) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by BalmaBrian** [comment]
error received after attempting second get request

**Comment by BalmaBrian** [comment]
Testing completed and first implication of serial port on this commit: [ea978a4](https://github.com/LiquidPropulsionGroup/EngineWebServer/commit/ea978a45e5f23ae9f399539c72c640c5e9958d63)
